// Code generated by Fabrica dev. DO NOT EDIT.
// Template: server/handlers.go.tmpl
// Generated: 2026-07-05T20:04:19Z
//
// # Copyright © 2026 OpenCHAMI a Series of LF Projects, LLC
//
// SPDX-License-Identifier: MIT
//
// This file contains REST API handlers for FirmwareUpdateCampaign resources.
//
// To modify this code:
//  1. Edit the template file: pkg/codegen/templates/handlers.go.tmpl
//  2. Run 'fabrica generate' to regenerate
//  3. Do NOT edit this file directly - changes will be lost
//
// Generated handlers provide:
//   - GET /firmwareupdatecampaigns (list all firmwareupdatecampaigns)
//   - GET /firmwareupdatecampaigns/{uid} (get specific FirmwareUpdateCampaign)
//   - POST /firmwareupdatecampaigns (create new FirmwareUpdateCampaign)
//   - PUT /firmwareupdatecampaigns/{uid} (update FirmwareUpdateCampaign spec)
//   - PATCH /firmwareupdatecampaigns/{uid} (patch FirmwareUpdateCampaign spec)
//   - DELETE /firmwareupdatecampaigns/{uid} (delete FirmwareUpdateCampaign)
//   - PUT /firmwareupdatecampaigns/{uid}/status (update FirmwareUpdateCampaign status)
//   - PATCH /firmwareupdatecampaigns/{uid}/status (patch FirmwareUpdateCampaign status)
//
// Authorization: Add custom middleware for authentication/authorization
// Storage: Uses storage.LoadFirmwareUpdateCampaign*/SaveFirmwareUpdateCampaign*/DeleteFirmwareUpdateCampaign*
// Version Support: Available (see version context in handlers)
//
// To enable full version conversion for this resource:
//  1. Add new version: fabrica add version <group> <version>
//  2. Implement converter: apis/<group>/<version>/converter.go
//  3. Add version-aware storage: storage.LoadFirmwareUpdateCampaignWithVersion()
//  4. Register versions in cmd/server/main.go
package main

import (
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/openchami/fabrica/pkg/events"
	"github.com/openchami/fabrica/pkg/patch"
	"github.com/openchami/fabrica/pkg/resource"
	"github.com/openchami/fabrica/pkg/validation"
	"github.com/openchami/fabrica/pkg/versioning"
	v1 "github.com/user/firmware-updater/apis/hardware.fabrica.dev/v1"

	"github.com/user/firmware-updater/internal/storage"
)

// GetFirmwareUpdateCampaigns returns all FirmwareUpdateCampaign resources
func GetFirmwareUpdateCampaigns(w http.ResponseWriter, r *http.Request) {
	// Authorization: Add custom middleware in routes.go or implement checks here
	// Example: if !authorized(r) { respondError(w, http.StatusUnauthorized, fmt.Errorf("unauthorized")); return }

	firmwareupdatecampaigns, err := storage.LoadAllFirmwareUpdateCampaigns(r.Context())
	if err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to load firmwareupdatecampaigns: %w", err))
		return
	}
	respondJSON(w, http.StatusOK, firmwareupdatecampaigns)
}

// GetFirmwareUpdateCampaign returns a specific FirmwareUpdateCampaign resource by UID
func GetFirmwareUpdateCampaign(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		respondError(w, http.StatusBadRequest, fmt.Errorf("FirmwareUpdateCampaign UID is required"))
		return
	}

	// Version context available here for version-aware operations
	// versionCtx := versioning.GetVersionContext(r.Context())
	// Requested version: versionCtx.ServeVersion
	// To enable: replace storage.LoadFirmwareUpdateCampaign() with version-aware function

	// Authorization: Add custom middleware in routes.go or implement checks here
	// Example: if !authorized(r) { respondError(w, http.StatusUnauthorized, fmt.Errorf("unauthorized")); return }

	firmwareUpdateCampaign, err := storage.LoadFirmwareUpdateCampaign(r.Context(), uid)
	if err != nil {
		respondError(w, http.StatusNotFound, fmt.Errorf("FirmwareUpdateCampaign not found: %w", err))
		return
	}
	respondJSON(w, http.StatusOK, firmwareUpdateCampaign)
}

// CreateFirmwareUpdateCampaign creates a new FirmwareUpdateCampaign resource
func CreateFirmwareUpdateCampaign(w http.ResponseWriter, r *http.Request) {
	var req CreateFirmwareUpdateCampaignRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("invalid request body: %w", err))
		return
	}

	// Layer 1: Request validation (validates inline spec fields and metadata)
	if err := validation.ValidateResource(&req); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("validation failed: %w", err))
		return
	}

	// Get version context from request (set by version negotiation middleware)
	versionCtx := versioning.GetVersionContext(r.Context())

	uid, err := resource.GenerateUIDForResource("FirmwareUpdateCampaign")
	if err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to generate UID: %w", err))
		return
	}

	// Versioned mode: flat fields with fabrica.Metadata
	firmwareUpdateCampaign := &v1.FirmwareUpdateCampaign{
		// Use negotiated ServeVersion (from Accept header) for apiVersion
		APIVersion: versionCtx.ServeVersion,
		Kind:       "FirmwareUpdateCampaign",
		Spec:       req.AsSpec(),
	}

	// Initialize metadata from request
	firmwareUpdateCampaign.Metadata = req.Metadata
	firmwareUpdateCampaign.Metadata.UID = uid
	now := time.Now()
	firmwareUpdateCampaign.Metadata.CreatedAt = now
	firmwareUpdateCampaign.Metadata.UpdatedAt = now

	// Set labels and annotations
	if firmwareUpdateCampaign.Metadata.Labels == nil {
		firmwareUpdateCampaign.Metadata.Labels = make(map[string]string)
	}
	for k, v := range req.Labels {
		firmwareUpdateCampaign.Metadata.Labels[k] = v
	}
	if firmwareUpdateCampaign.Metadata.Annotations == nil {
		firmwareUpdateCampaign.Metadata.Annotations = make(map[string]string)
	}
	for k, v := range req.Annotations {
		firmwareUpdateCampaign.Metadata.Annotations[k] = v
	}

	// Layer 2: Custom business logic validation
	if err := validation.ValidateWithContext(r.Context(), firmwareUpdateCampaign); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("validation failed: %w", err))
		return
	}

	// Set initial status
	// This assumes the generator passes an 'IsReconcilable' boolean
	// to this template, and that the resource has a .Status.Phase field.

	// Save (Layer 1: Ent validation happens automatically if using Ent storage)
	if err := storage.SaveFirmwareUpdateCampaign(r.Context(), firmwareUpdateCampaign); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to save FirmwareUpdateCampaign: %w", err))
		return
	}

	// Publish resource created event

	if err := events.PublishResourceCreated(r.Context(), "FirmwareUpdateCampaign", firmwareUpdateCampaign.Metadata.UID, firmwareUpdateCampaign.Metadata.Name, firmwareUpdateCampaign); err != nil {
		// Log the error but don't fail the request - events are non-critical
		fmt.Printf("Warning: Failed to publish resource created event for FirmwareUpdateCampaign %s: %v\n", firmwareUpdateCampaign.Metadata.UID, err)

	}

	respondJSON(w, http.StatusCreated, firmwareUpdateCampaign)
}

// UpdateFirmwareUpdateCampaign updates the spec of an existing FirmwareUpdateCampaign resource
// NOTE: This endpoint ONLY updates the spec. Use PUT //firmwareupdatecampaigns/{uid}/status to update status.
func UpdateFirmwareUpdateCampaign(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		respondError(w, http.StatusBadRequest, fmt.Errorf("FirmwareUpdateCampaign UID is required"))
		return
	}

	firmwareUpdateCampaign, err := storage.LoadFirmwareUpdateCampaign(r.Context(), uid)
	if err != nil {
		respondError(w, http.StatusNotFound, fmt.Errorf("FirmwareUpdateCampaign not found: %w", err))
		return
	}

	var req UpdateFirmwareUpdateCampaignRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("invalid request body: %w", err))
		return
	}

	// Apply updates

	// Versioned mode: direct field access
	if req.Metadata.Name != "" {
		firmwareUpdateCampaign.Metadata.Name = req.Metadata.Name
	}

	// Update spec fields ONLY - status should use /status subresource
	firmwareUpdateCampaign.Spec = req.AsSpec()

	// Update labels and annotations
	if firmwareUpdateCampaign.Metadata.Labels == nil {
		firmwareUpdateCampaign.Metadata.Labels = make(map[string]string)
	}
	for k, v := range req.Labels {
		firmwareUpdateCampaign.Metadata.Labels[k] = v
	}
	if firmwareUpdateCampaign.Metadata.Annotations == nil {
		firmwareUpdateCampaign.Metadata.Annotations = make(map[string]string)
	}
	for k, v := range req.Annotations {
		firmwareUpdateCampaign.Metadata.Annotations[k] = v
	}

	// Update timestamp
	firmwareUpdateCampaign.Metadata.UpdatedAt = time.Now()

	// Layer 2: Custom business logic validation
	if err := validation.ValidateWithContext(r.Context(), firmwareUpdateCampaign); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("validation failed: %w", err))
		return
	}

	if err := storage.SaveFirmwareUpdateCampaign(r.Context(), firmwareUpdateCampaign); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to save FirmwareUpdateCampaign: %w", err))
		return
	}

	// Publish resource updated event
	updateMetadata := map[string]interface{}{
		"updatedAt": firmwareUpdateCampaign.Metadata.UpdatedAt,
	}

	if err := events.PublishResourceUpdated(r.Context(), "FirmwareUpdateCampaign", firmwareUpdateCampaign.Metadata.UID, firmwareUpdateCampaign.Metadata.Name, firmwareUpdateCampaign, updateMetadata); err != nil {
		// Log the error but don't fail the request - events are non-critical
		fmt.Printf("Warning: Failed to publish resource updated event for FirmwareUpdateCampaign %s: %v\n", firmwareUpdateCampaign.Metadata.UID, err)

	}

	respondJSON(w, http.StatusOK, firmwareUpdateCampaign)
}

// PatchFirmwareUpdateCampaign patches an existing FirmwareUpdateCampaign resource spec using JSON Merge Patch, JSON Patch, or Shorthand Patch
// Only the spec portion of the resource can be patched - metadata and status are API-managed
func PatchFirmwareUpdateCampaign(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		respondError(w, http.StatusBadRequest, fmt.Errorf("FirmwareUpdateCampaign UID is required"))
		return
	}

	firmwareUpdateCampaign, err := storage.LoadFirmwareUpdateCampaign(r.Context(), uid)
	if err != nil {
		respondError(w, http.StatusNotFound, fmt.Errorf("FirmwareUpdateCampaign not found: %w", err))
		return
	}

	// Read patch document
	patchData, err := io.ReadAll(r.Body)
	if err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("failed to read patch data: %w", err))
		return
	}

	// Marshal current spec to JSON for patching (only allow spec modifications)
	currentSpecJSON, err := json.Marshal(firmwareUpdateCampaign.Spec)
	if err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to marshal current spec: %w", err))
		return
	}

	// Detect patch type from Content-Type header
	contentType := r.Header.Get("Content-Type")
	patchType := patch.DetectPatchType(contentType)

	// Apply patch to spec only
	patchResult, err := patch.ApplyPatchWithOptions(currentSpecJSON, patchData, patchType, patch.PatchOptions{
		AllowAddFields:    true,
		AllowRemoveFields: true,
	})
	if err != nil {
		respondError(w, http.StatusUnprocessableEntity, fmt.Errorf("failed to apply patch to spec: %w", err))
		return
	}

	// Unmarshal the patched result back to the spec
	if err := json.Unmarshal(patchResult.Updated, &firmwareUpdateCampaign.Spec); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to unmarshal patched spec: %w", err))
		return
	}

	// Touch to update metadata

	firmwareUpdateCampaign.Metadata.UpdatedAt = time.Now()

	// Layer 2: Custom business logic validation
	if err := validation.ValidateWithContext(r.Context(), firmwareUpdateCampaign); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("validation failed: %w", err))
		return
	}

	// Save the patched resource
	if err := storage.SaveFirmwareUpdateCampaign(r.Context(), firmwareUpdateCampaign); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to save patched FirmwareUpdateCampaign: %w", err))
		return
	}

	// Publish resource patched event
	patchMetadata := map[string]interface{}{
		"patchType": patchType,
		"updatedAt": firmwareUpdateCampaign.Metadata.UpdatedAt,
	}

	if err := events.PublishResourcePatched(r.Context(), "FirmwareUpdateCampaign", firmwareUpdateCampaign.Metadata.UID, firmwareUpdateCampaign.Metadata.Name, firmwareUpdateCampaign, patchMetadata); err != nil {
		// Log the error but don't fail the request - events are non-critical
		fmt.Printf("Warning: Failed to publish resource patched event for FirmwareUpdateCampaign %s: %v\n", firmwareUpdateCampaign.Metadata.UID, err)

	}

	respondJSON(w, http.StatusOK, firmwareUpdateCampaign)
}

// UpdateFirmwareUpdateCampaignStatus updates only the status of a FirmwareUpdateCampaign resource
// This endpoint is intended for controllers, reconcilers, and monitoring systems.
// It does not modify the spec or metadata (except updatedAt timestamp).
//
// Authorization: Requires 'update_status' permission (separate from 'update' permission)
// Events: Publishes resource updated event with updateType: "status"
func UpdateFirmwareUpdateCampaignStatus(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		respondError(w, http.StatusBadRequest, fmt.Errorf("FirmwareUpdateCampaign UID is required"))
		return
	}

	// Authorization: Add custom middleware for status update authorization
	// Status updates can have different permissions than spec updates

	res, err := storage.LoadFirmwareUpdateCampaign(r.Context(), uid)
	if err != nil {
		respondError(w, http.StatusNotFound, fmt.Errorf("FirmwareUpdateCampaign not found: %w", err))
		return
	}

	var statusUpdate v1.FirmwareUpdateCampaignStatus
	if err := json.NewDecoder(r.Body).Decode(&statusUpdate); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("invalid status body: %w", err))
		return
	}

	// Preserve spec - only update status
	res.Status = statusUpdate

	res.Metadata.UpdatedAt = time.Now()

	// Layer 2: Custom business logic validation
	if err := validation.ValidateWithContext(r.Context(), res); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("validation failed: %w", err))
		return
	}

	if err := storage.SaveFirmwareUpdateCampaign(r.Context(), res); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to save FirmwareUpdateCampaign status: %w", err))
		return
	}

	// Publish status update event
	statusMetadata := map[string]interface{}{
		"updatedAt":  res.Metadata.UpdatedAt,
		"updateType": "status",
	}

	if err := events.PublishResourceUpdated(r.Context(), "FirmwareUpdateCampaign", res.Metadata.UID, res.Metadata.Name, res, statusMetadata); err != nil {
		// Log but don't fail - events are non-critical
		fmt.Printf("Warning: Failed to publish status update event for FirmwareUpdateCampaign %s: %v\n", res.Metadata.UID, err)

	}

	respondJSON(w, http.StatusOK, res)
}

// PatchFirmwareUpdateCampaignStatus patches only the status of a FirmwareUpdateCampaign resource
// Supports JSON Merge Patch, JSON Patch, and Shorthand Patch formats.
// Only modifies status fields - spec and metadata are preserved.
func PatchFirmwareUpdateCampaignStatus(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		respondError(w, http.StatusBadRequest, fmt.Errorf("FirmwareUpdateCampaign UID is required"))
		return
	}

	// Authorization: Add custom middleware for status patch authorization
	// Status patches can have different permissions than spec patches

	res, err := storage.LoadFirmwareUpdateCampaign(r.Context(), uid)
	if err != nil {
		respondError(w, http.StatusNotFound, fmt.Errorf("FirmwareUpdateCampaign not found: %w", err))
		return
	}

	patchData, err := io.ReadAll(r.Body)
	if err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("failed to read patch data: %w", err))
		return
	}

	// Marshal current status for patching
	currentStatusJSON, err := json.Marshal(res.Status)
	if err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to marshal current status: %w", err))
		return
	}

	contentType := r.Header.Get("Content-Type")
	patchType := patch.DetectPatchType(contentType)

	patchResult, err := patch.ApplyPatchWithOptions(currentStatusJSON, patchData, patchType, patch.PatchOptions{
		AllowAddFields:    true,
		AllowRemoveFields: false, // Don't allow removing status fields
	})
	if err != nil {
		respondError(w, http.StatusUnprocessableEntity, fmt.Errorf("failed to apply patch to status: %w", err))
		return
	}

	// Unmarshal patched status back
	if err := json.Unmarshal(patchResult.Updated, &res.Status); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to unmarshal patched status: %w", err))
		return
	}

	res.Metadata.UpdatedAt = time.Now()

	// Layer 2: Custom business logic validation
	if err := validation.ValidateWithContext(r.Context(), res); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("validation failed: %w", err))
		return
	}

	if err := storage.SaveFirmwareUpdateCampaign(r.Context(), res); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to save patched FirmwareUpdateCampaign status: %w", err))
		return
	}

	// Publish status patch event
	patchMetadata := map[string]interface{}{
		"patchType":  patchType,
		"updatedAt":  res.Metadata.UpdatedAt,
		"updateType": "status",
	}

	if err := events.PublishResourcePatched(r.Context(), "FirmwareUpdateCampaign", res.Metadata.UID, res.Metadata.Name, res, patchMetadata); err != nil {
		fmt.Printf("Warning: Failed to publish status patch event for FirmwareUpdateCampaign %s: %v\n", res.Metadata.UID, err)

	}

	respondJSON(w, http.StatusOK, res)
}

// DeleteFirmwareUpdateCampaign deletes a FirmwareUpdateCampaign resource
func DeleteFirmwareUpdateCampaign(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		respondError(w, http.StatusBadRequest, fmt.Errorf("FirmwareUpdateCampaign UID is required"))
		return
	}

	// Load resource before deletion for event publishing
	firmwareUpdateCampaign, err := storage.LoadFirmwareUpdateCampaign(r.Context(), uid)
	if err != nil {
		respondError(w, http.StatusNotFound, fmt.Errorf("FirmwareUpdateCampaign not found: %w", err))
		return
	}

	if err := storage.DeleteFirmwareUpdateCampaign(r.Context(), uid); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to delete FirmwareUpdateCampaign: %w", err))
		return
	}

	// Publish resource deleted event
	deleteMetadata := map[string]interface{}{
		"deletedAt": time.Now(),
	}

	if err := events.PublishResourceDeleted(r.Context(), "FirmwareUpdateCampaign", firmwareUpdateCampaign.Metadata.UID, firmwareUpdateCampaign.Metadata.Name, deleteMetadata); err != nil {
		// Log the error but don't fail the request - events are non-critical
		fmt.Printf("Warning: Failed to publish resource deleted event for FirmwareUpdateCampaign %s: %v\n", firmwareUpdateCampaign.Metadata.UID, err)

	}

	respondJSON(w, http.StatusOK, &DeleteResponse{
		Message: "FirmwareUpdateCampaign deleted successfully",
		UID:     uid,
	})
}
