// Code generated by Fabrica dev. DO NOT EDIT.
// Template: server/handlers.go.tmpl
// Generated: 2026-06-01T19:11:44Z
//
// # Copyright © 2026 OpenCHAMI a Series of LF Projects, LLC
//
// SPDX-License-Identifier: MIT
//
// This file contains REST API handlers for FirmwareBundle resources.
//
// To modify this code:
//  1. Edit the template file: pkg/codegen/templates/handlers.go.tmpl
//  2. Run 'fabrica generate' to regenerate
//  3. Do NOT edit this file directly - changes will be lost
//
// Generated handlers provide:
//   - GET /firmwarebundles (list all firmwarebundles)
//   - GET /firmwarebundles/{uid} (get specific FirmwareBundle)
//   - POST /firmwarebundles (create new FirmwareBundle)
//   - PUT /firmwarebundles/{uid} (update FirmwareBundle spec)
//   - PATCH /firmwarebundles/{uid} (patch FirmwareBundle spec)
//   - DELETE /firmwarebundles/{uid} (delete FirmwareBundle)
//   - PUT /firmwarebundles/{uid}/status (update FirmwareBundle status)
//   - PATCH /firmwarebundles/{uid}/status (patch FirmwareBundle status)
//
// Authorization: Add custom middleware for authentication/authorization
// Storage: Uses storage.LoadFirmwareBundle*/SaveFirmwareBundle*/DeleteFirmwareBundle*
// Version Support: Available (see version context in handlers)
//
// To enable full version conversion for this resource:
//  1. Add new version: fabrica add version <group> <version>
//  2. Implement converter: apis/<group>/<version>/converter.go
//  3. Add version-aware storage: storage.LoadFirmwareBundleWithVersion()
//  4. Register versions in cmd/server/main.go
package main

import (
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"time"

	v1 "firmware-manager/apis/hardware.fabrica.dev/v1"
	"github.com/go-chi/chi/v5"
	"github.com/openchami/fabrica/pkg/events"
	"github.com/openchami/fabrica/pkg/patch"
	"github.com/openchami/fabrica/pkg/resource"
	"github.com/openchami/fabrica/pkg/validation"
	"github.com/openchami/fabrica/pkg/versioning"

	"firmware-manager/internal/storage"
)

// GetFirmwareBundles returns all FirmwareBundle resources
func GetFirmwareBundles(w http.ResponseWriter, r *http.Request) {
	// Authorization: Add custom middleware in routes.go or implement checks here
	// Example: if !authorized(r) { respondError(w, http.StatusUnauthorized, fmt.Errorf("unauthorized")); return }

	firmwarebundles, err := storage.LoadAllFirmwareBundles(r.Context())
	if err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to load firmwarebundles: %w", err))
		return
	}
	respondJSON(w, http.StatusOK, firmwarebundles)
}

// GetFirmwareBundle returns a specific FirmwareBundle resource by UID
func GetFirmwareBundle(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		respondError(w, http.StatusBadRequest, fmt.Errorf("FirmwareBundle UID is required"))
		return
	}

	// Version context available here for version-aware operations
	// versionCtx := versioning.GetVersionContext(r.Context())
	// Requested version: versionCtx.ServeVersion
	// To enable: replace storage.LoadFirmwareBundle() with version-aware function

	// Authorization: Add custom middleware in routes.go or implement checks here
	// Example: if !authorized(r) { respondError(w, http.StatusUnauthorized, fmt.Errorf("unauthorized")); return }

	firmwareBundle, err := storage.LoadFirmwareBundle(r.Context(), uid)
	if err != nil {
		respondError(w, http.StatusNotFound, fmt.Errorf("FirmwareBundle not found: %w", err))
		return
	}
	respondJSON(w, http.StatusOK, firmwareBundle)
}

// CreateFirmwareBundle creates a new FirmwareBundle resource
func CreateFirmwareBundle(w http.ResponseWriter, r *http.Request) {
	var req CreateFirmwareBundleRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("invalid request body: %w", err))
		return
	}

	// Layer 1: Request validation (validates inline spec fields and metadata)
	if err := validation.ValidateResource(&req); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("validation failed: %w", err))
		return
	}

	// Get version context from request (set by version negotiation middleware)
	versionCtx := versioning.GetVersionContext(r.Context())

	uid, err := resource.GenerateUIDForResource("FirmwareBundle")
	if err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to generate UID: %w", err))
		return
	}

	// Versioned mode: flat fields with fabrica.Metadata
	firmwareBundle := &v1.FirmwareBundle{
		// Use negotiated ServeVersion (from Accept header) for apiVersion
		APIVersion: versionCtx.ServeVersion,
		Kind:       "FirmwareBundle",
		Spec:       req.AsSpec(),
	}

	// Initialize metadata from request
	firmwareBundle.Metadata = req.Metadata
	firmwareBundle.Metadata.UID = uid
	now := time.Now()
	firmwareBundle.Metadata.CreatedAt = now
	firmwareBundle.Metadata.UpdatedAt = now

	// Set labels and annotations
	if firmwareBundle.Metadata.Labels == nil {
		firmwareBundle.Metadata.Labels = make(map[string]string)
	}
	for k, v := range req.Labels {
		firmwareBundle.Metadata.Labels[k] = v
	}
	if firmwareBundle.Metadata.Annotations == nil {
		firmwareBundle.Metadata.Annotations = make(map[string]string)
	}
	for k, v := range req.Annotations {
		firmwareBundle.Metadata.Annotations[k] = v
	}

	// Layer 2: Custom business logic validation
	if err := validation.ValidateWithContext(r.Context(), firmwareBundle); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("validation failed: %w", err))
		return
	}

	// Set initial status
	// This assumes the generator passes an 'IsReconcilable' boolean
	// to this template, and that the resource has a .Status.Phase field.

	// Save (Layer 1: Ent validation happens automatically if using Ent storage)
	if err := storage.SaveFirmwareBundle(r.Context(), firmwareBundle); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to save FirmwareBundle: %w", err))
		return
	}

	// Publish resource created event

	if err := events.PublishResourceCreated(r.Context(), "FirmwareBundle", firmwareBundle.Metadata.UID, firmwareBundle.Metadata.Name, firmwareBundle); err != nil {
		// Log the error but don't fail the request - events are non-critical
		fmt.Printf("Warning: Failed to publish resource created event for FirmwareBundle %s: %v\n", firmwareBundle.Metadata.UID, err)

	}

	respondJSON(w, http.StatusCreated, firmwareBundle)
}

// UpdateFirmwareBundle updates the spec of an existing FirmwareBundle resource
// NOTE: This endpoint ONLY updates the spec. Use PUT //firmwarebundles/{uid}/status to update status.
func UpdateFirmwareBundle(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		respondError(w, http.StatusBadRequest, fmt.Errorf("FirmwareBundle UID is required"))
		return
	}

	firmwareBundle, err := storage.LoadFirmwareBundle(r.Context(), uid)
	if err != nil {
		respondError(w, http.StatusNotFound, fmt.Errorf("FirmwareBundle not found: %w", err))
		return
	}

	var req UpdateFirmwareBundleRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("invalid request body: %w", err))
		return
	}

	// Apply updates

	// Versioned mode: direct field access
	if req.Metadata.Name != "" {
		firmwareBundle.Metadata.Name = req.Metadata.Name
	}

	// Update spec fields ONLY - status should use /status subresource
	firmwareBundle.Spec = req.AsSpec()

	// Update labels and annotations
	if firmwareBundle.Metadata.Labels == nil {
		firmwareBundle.Metadata.Labels = make(map[string]string)
	}
	for k, v := range req.Labels {
		firmwareBundle.Metadata.Labels[k] = v
	}
	if firmwareBundle.Metadata.Annotations == nil {
		firmwareBundle.Metadata.Annotations = make(map[string]string)
	}
	for k, v := range req.Annotations {
		firmwareBundle.Metadata.Annotations[k] = v
	}

	// Update timestamp
	firmwareBundle.Metadata.UpdatedAt = time.Now()

	// Layer 2: Custom business logic validation
	if err := validation.ValidateWithContext(r.Context(), firmwareBundle); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("validation failed: %w", err))
		return
	}

	if err := storage.SaveFirmwareBundle(r.Context(), firmwareBundle); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to save FirmwareBundle: %w", err))
		return
	}

	// Publish resource updated event
	updateMetadata := map[string]interface{}{
		"updatedAt": firmwareBundle.Metadata.UpdatedAt,
	}

	if err := events.PublishResourceUpdated(r.Context(), "FirmwareBundle", firmwareBundle.Metadata.UID, firmwareBundle.Metadata.Name, firmwareBundle, updateMetadata); err != nil {
		// Log the error but don't fail the request - events are non-critical
		fmt.Printf("Warning: Failed to publish resource updated event for FirmwareBundle %s: %v\n", firmwareBundle.Metadata.UID, err)

	}

	respondJSON(w, http.StatusOK, firmwareBundle)
}

// PatchFirmwareBundle patches an existing FirmwareBundle resource spec using JSON Merge Patch, JSON Patch, or Shorthand Patch
// Only the spec portion of the resource can be patched - metadata and status are API-managed
func PatchFirmwareBundle(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		respondError(w, http.StatusBadRequest, fmt.Errorf("FirmwareBundle UID is required"))
		return
	}

	firmwareBundle, err := storage.LoadFirmwareBundle(r.Context(), uid)
	if err != nil {
		respondError(w, http.StatusNotFound, fmt.Errorf("FirmwareBundle not found: %w", err))
		return
	}

	// Read patch document
	patchData, err := io.ReadAll(r.Body)
	if err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("failed to read patch data: %w", err))
		return
	}

	// Marshal current spec to JSON for patching (only allow spec modifications)
	currentSpecJSON, err := json.Marshal(firmwareBundle.Spec)
	if err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to marshal current spec: %w", err))
		return
	}

	// Detect patch type from Content-Type header
	contentType := r.Header.Get("Content-Type")
	patchType := patch.DetectPatchType(contentType)

	// Apply patch to spec only
	patchResult, err := patch.ApplyPatchWithOptions(currentSpecJSON, patchData, patchType, patch.PatchOptions{
		AllowAddFields:    true,
		AllowRemoveFields: true,
	})
	if err != nil {
		respondError(w, http.StatusUnprocessableEntity, fmt.Errorf("failed to apply patch to spec: %w", err))
		return
	}

	// Unmarshal the patched result back to the spec
	if err := json.Unmarshal(patchResult.Updated, &firmwareBundle.Spec); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to unmarshal patched spec: %w", err))
		return
	}

	// Touch to update metadata

	firmwareBundle.Metadata.UpdatedAt = time.Now()

	// Layer 2: Custom business logic validation
	if err := validation.ValidateWithContext(r.Context(), firmwareBundle); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("validation failed: %w", err))
		return
	}

	// Save the patched resource
	if err := storage.SaveFirmwareBundle(r.Context(), firmwareBundle); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to save patched FirmwareBundle: %w", err))
		return
	}

	// Publish resource patched event
	patchMetadata := map[string]interface{}{
		"patchType": patchType,
		"updatedAt": firmwareBundle.Metadata.UpdatedAt,
	}

	if err := events.PublishResourcePatched(r.Context(), "FirmwareBundle", firmwareBundle.Metadata.UID, firmwareBundle.Metadata.Name, firmwareBundle, patchMetadata); err != nil {
		// Log the error but don't fail the request - events are non-critical
		fmt.Printf("Warning: Failed to publish resource patched event for FirmwareBundle %s: %v\n", firmwareBundle.Metadata.UID, err)

	}

	respondJSON(w, http.StatusOK, firmwareBundle)
}

// UpdateFirmwareBundleStatus updates only the status of a FirmwareBundle resource
// This endpoint is intended for controllers, reconcilers, and monitoring systems.
// It does not modify the spec or metadata (except updatedAt timestamp).
//
// Authorization: Requires 'update_status' permission (separate from 'update' permission)
// Events: Publishes resource updated event with updateType: "status"
func UpdateFirmwareBundleStatus(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		respondError(w, http.StatusBadRequest, fmt.Errorf("FirmwareBundle UID is required"))
		return
	}

	// Authorization: Add custom middleware for status update authorization
	// Status updates can have different permissions than spec updates

	res, err := storage.LoadFirmwareBundle(r.Context(), uid)
	if err != nil {
		respondError(w, http.StatusNotFound, fmt.Errorf("FirmwareBundle not found: %w", err))
		return
	}

	var statusUpdate v1.FirmwareBundleStatus
	if err := json.NewDecoder(r.Body).Decode(&statusUpdate); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("invalid status body: %w", err))
		return
	}

	// Preserve spec - only update status
	res.Status = statusUpdate

	res.Metadata.UpdatedAt = time.Now()

	// Layer 2: Custom business logic validation
	if err := validation.ValidateWithContext(r.Context(), res); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("validation failed: %w", err))
		return
	}

	if err := storage.SaveFirmwareBundle(r.Context(), res); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to save FirmwareBundle status: %w", err))
		return
	}

	// Publish status update event
	statusMetadata := map[string]interface{}{
		"updatedAt":  res.Metadata.UpdatedAt,
		"updateType": "status",
	}

	if err := events.PublishResourceUpdated(r.Context(), "FirmwareBundle", res.Metadata.UID, res.Metadata.Name, res, statusMetadata); err != nil {
		// Log but don't fail - events are non-critical
		fmt.Printf("Warning: Failed to publish status update event for FirmwareBundle %s: %v\n", res.Metadata.UID, err)

	}

	respondJSON(w, http.StatusOK, res)
}

// PatchFirmwareBundleStatus patches only the status of a FirmwareBundle resource
// Supports JSON Merge Patch, JSON Patch, and Shorthand Patch formats.
// Only modifies status fields - spec and metadata are preserved.
func PatchFirmwareBundleStatus(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		respondError(w, http.StatusBadRequest, fmt.Errorf("FirmwareBundle UID is required"))
		return
	}

	// Authorization: Add custom middleware for status patch authorization
	// Status patches can have different permissions than spec patches

	res, err := storage.LoadFirmwareBundle(r.Context(), uid)
	if err != nil {
		respondError(w, http.StatusNotFound, fmt.Errorf("FirmwareBundle not found: %w", err))
		return
	}

	patchData, err := io.ReadAll(r.Body)
	if err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("failed to read patch data: %w", err))
		return
	}

	// Marshal current status for patching
	currentStatusJSON, err := json.Marshal(res.Status)
	if err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to marshal current status: %w", err))
		return
	}

	contentType := r.Header.Get("Content-Type")
	patchType := patch.DetectPatchType(contentType)

	patchResult, err := patch.ApplyPatchWithOptions(currentStatusJSON, patchData, patchType, patch.PatchOptions{
		AllowAddFields:    true,
		AllowRemoveFields: false, // Don't allow removing status fields
	})
	if err != nil {
		respondError(w, http.StatusUnprocessableEntity, fmt.Errorf("failed to apply patch to status: %w", err))
		return
	}

	// Unmarshal patched status back
	if err := json.Unmarshal(patchResult.Updated, &res.Status); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to unmarshal patched status: %w", err))
		return
	}

	res.Metadata.UpdatedAt = time.Now()

	// Layer 2: Custom business logic validation
	if err := validation.ValidateWithContext(r.Context(), res); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("validation failed: %w", err))
		return
	}

	if err := storage.SaveFirmwareBundle(r.Context(), res); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to save patched FirmwareBundle status: %w", err))
		return
	}

	// Publish status patch event
	patchMetadata := map[string]interface{}{
		"patchType":  patchType,
		"updatedAt":  res.Metadata.UpdatedAt,
		"updateType": "status",
	}

	if err := events.PublishResourcePatched(r.Context(), "FirmwareBundle", res.Metadata.UID, res.Metadata.Name, res, patchMetadata); err != nil {
		fmt.Printf("Warning: Failed to publish status patch event for FirmwareBundle %s: %v\n", res.Metadata.UID, err)

	}

	respondJSON(w, http.StatusOK, res)
}

// DeleteFirmwareBundle deletes a FirmwareBundle resource
func DeleteFirmwareBundle(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		respondError(w, http.StatusBadRequest, fmt.Errorf("FirmwareBundle UID is required"))
		return
	}

	// Load resource before deletion for event publishing
	firmwareBundle, err := storage.LoadFirmwareBundle(r.Context(), uid)
	if err != nil {
		respondError(w, http.StatusNotFound, fmt.Errorf("FirmwareBundle not found: %w", err))
		return
	}

	if err := storage.DeleteFirmwareBundle(r.Context(), uid); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to delete FirmwareBundle: %w", err))
		return
	}

	// Publish resource deleted event
	deleteMetadata := map[string]interface{}{
		"deletedAt": time.Now(),
	}

	if err := events.PublishResourceDeleted(r.Context(), "FirmwareBundle", firmwareBundle.Metadata.UID, firmwareBundle.Metadata.Name, deleteMetadata); err != nil {
		// Log the error but don't fail the request - events are non-critical
		fmt.Printf("Warning: Failed to publish resource deleted event for FirmwareBundle %s: %v\n", firmwareBundle.Metadata.UID, err)

	}

	respondJSON(w, http.StatusOK, &DeleteResponse{
		Message: "FirmwareBundle deleted successfully",
		UID:     uid,
	})
}
